title       :      victor
tagline     :      desenvolvedor frontend
description :      Oi, meu nome Ã© Victor, tenho 21 anos e trabalho como desenvolvedor front-end desde 2013

# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://victormartins.com.br
enforce_ssl:      victormartins.com.br

# theme color
theme_color: "#2c3e50"


# Owner/author information
social:
  email:          victorfrontend@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  username:       prescindivel
  github:         victordev
  linkedin:       victormartins4
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    +VictorMartinsDev

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-48294521-1
google_verify:      Vk_OznIkGCtWe_l4ODtYatwsFu-qWk0yt-VHD2ILQBQ

# Links to include in top navigation
links:
  - title: blog
    url: /blog/
  - title: projetos
    url: /projects/
  - title: sobre
    url: /about/
  - title: contato
    url: /contact/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Fortaleza
future:      true

markdown:    kramdown
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

exclude: [".jekyll-metadata", "Gemfile", "Rakefile.rb", "scripts", "Gemfile.lock", ".gitignore", "node_modules", "package.json", "gulpfile.js", "assets/sass"]

encoding: utf-8
lang: pt-BR

gems:
  - jekyll-sitemap
