title       :      victor
tagline     :      desenvolvedor frontend
description :      Oi, meu nome Ã© Victor, tenho 21 anos e trabalho como desenvolvedor front-end desde 2013

# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://192.168.0.41:4000
# url:              https://victormartins.com.br
enforce_ssl:      victormartins.com.br


# Owner/author information
social:
  avatar:         "https://avatars2.githubusercontent.com/u/6462673?v=3&s=460"
  email:          victorfrontend@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        prescindivel
  facebook:       prescindivel
  github:         victordev
  linkedin:       victormartins4
  instagram:      prescindivel
  lastfm:         prescindivel
  pinterest:      prescindivel
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    +VictorMartinsDev

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-48294521-1
google_verify:      Vk_OznIkGCtWe_l4ODtYatwsFu-qWk0yt-VHD2ILQBQ

# Links to include in top navigation
# For external links add external: true
links:
  - title: sobre
    url: /sobre/
  - title: artigos
    url: /artigos/
  - title: projetos
    url: /projetos/
  - title: contato
    url: /contato/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Fortaleza
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

exclude: ["Gemfile", "Gemfile.lock", ".gitignore", "node_modules", "package.json", "gulpfile.js", "assets/sass"]


encoding: utf-8
lang: pt-BR
